### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create HTML skeleton 
- [x] set entire page to a green color
- [x] create div element to contain the img of car
- [x] find img of car and add it inside the div
- [x] size the car to an appropriate size
- [x] make sure color and img are adequate
