### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create data model that includes which direction car is facing, maybe add other details?
- [x] create css classes that determine which way the car is facing
- [x] possibly add transition effects to make the movement smooth
- [x] listen for keydown event 
- [x] for each keydown event, that will determine direction car is facing
