### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add a location to the data model that holds the car's x and y coordinates on the page
- [x] use absolute position on the car so it can move across the page.
- [x] read up on the 'style' property of an element
- [x] use it to change the car's top and left box offset styles.
- [x] use 16 milliseconds for a smooth movement look
- [x] probably have to use setInterval to repeat the movement in the car?
