### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Create a conditional statement
- [x] if the user does not stop the car, it goes off the page
- [x] keydown with space bar to stop the car
- [x] if pressed again car starts
- [x] Able to stop the car whenever?
