### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Jykwon24** [Jykwon24/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] keydown events to steer the car in each direction
- [x] change the car's location based on which direction it is facing?
- [x] fix all errors
